.TH install-gui "1" "January 2015" "install-gui" "User Commands (1)"
.SH NAME
install-gui - Installer for fullstory/ aptosid based live systems
.SH SYNOPSIS
.B install-gui.bash
.SH DESCRIPTION
`install-gui' provides a graphical frontend for installing fullstory/ aptosid
based live systems. It creates the configuration file for fll-installer,
invokes it and keeps track of the installation status via inotify.
.SH "SEE ALSO"
.BR fll-installer
.SH AUTHOR
This manual has been written by Stefan Lippers-Hollmann <s.l-h@gmx.de> for 
the Debian project (but may be used by others).
