#!/bin/bash
#
# Copyright: © 2007-2008 Horst Tritremmel <hjt@users.berlios.de>
# License: GPL-2
#   The install-gui program is licensed under the GNU General Public License,
#   version 2.
#
export SSFT_FRONTEND=zenity

INETCONN=$(which inetconn) ||	INETCONN="/usr/bin/inetconn"

# connection test
printf "Internet connection test ...\n"
source $INETCONN
if [ "$connection" -eq 0 ]
	then
		exit 1
fi

curDir=$(dirname $0)

x-terminal-emulator -e ${curDir}/fw-install-exec &
