/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_main (void);
GtkWidget* create_dialog_no_root (void);
GtkWidget* create_install_progressbar (void);
GtkWidget* create_dialog_end (void);
GtkWidget* create_dialog_keyb_change (void);
